### ISSUE TITLE
Vapoursynth plugin 

### ISSUE THREAD

**Issue by adamcarter1** [imxieyi/waifu2x-mac#22]
Could you possibly make a Vapoursynth plugin that is mac compatible using metal so this could be added to workflow scripts of animation videos. 

Rather than a stand alone app or cli?

**Comment by imxieyi** [comment]
This use case is complicated and only very specific people will use it. I don't think it is worth so much effort in this project. I saw that you also created an issue in [vapoursynth-waifu2x-ncnn-vulkan](https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan/issues/4) which is based on waifu2x-ncnn-vulkan. It makes more sense porting an existing solution instead of creating a new one here from ground up.
