### ISSUE TITLE
Outputting Blank Images

### ISSUE THREAD

**Issue by nikhiljha** [imxieyi/waifu2x-mac#3]
I did `../waifu2x-mac-cli/waifu2x -t a -s 2 -n 2 -i "$file" -o "output/$file"` to upscale some files, but it outputs a blank image at output/$file.

```
2018-06-23 10:18:15.601 waifu2x[82288:1013507] Maximum texture size supported: 16384
"With Alpha: true"
"Really With Alpha: true"
```

I tried other image files (jpeg) and they work great, but there seems to be an issue either with transparency or file size. The exact images I was upscaling can be found here: https://drive.google.com/drive/folders/1Ok9QfoeLz0XKYUBOHC5aVq4JWXhzyCas

**Comment by nikhiljha** [comment]
<img width="1392" alt="screen shot 2018-06-23 at 10 21 25 am" src="https://user-images.githubusercontent.com/2773700/41812002-48793894-76cf-11e8-9ed7-ef534d9fdbce.png">

The same result in the non-cli version as well.

**Comment by imxieyi** [comment]
Hi @nikhiljha. I tried the same image as shown on your screenshot but it works fine:
![image](https://user-images.githubusercontent.com/20365903/41812155-1a31ac60-7750-11e8-92fc-985c5a4cc5ea.png)
The size of the image is 200x200. It should work fine on any computer.
I guess the issue is with Metal. Can you try to comment out [this if block](https://github.com/imxieyi/waifu2x-mac/blob/master/waifu2x-mac/Waifu2x.swift#L107) and see if it works? Without Metal support the code should be platform-independent, although the performance would suffer from this.

**Comment by nikhiljha** [comment]
Yup, it works fine without that if block.

**Comment by nikhiljha** [comment]
I do have a Macbook Pro with a dedicated GPU though, so it probably should work (?)

If not, maybe it should detect the empty image and fallback to non-metal if necessary, it was "only" about 3x slower without metal.

**Comment by imxieyi** [comment]
This feature has been implemented in the latest version.
